Load Football-data.org data

Leagues

In [15]:
import requests
import json
from pathlib import Path
import os
import boto3
from dotenv import load_dotenv
load_dotenv()

# ---- Configure these ----
URL = "https://api.football-data.org/v4/competitions/PL"
METHOD = "GET"
HEADERS = {
    "X-Auth-Token": os.getenv("FOOTBALL_DATA_ORG_API_KEY"),
}
PARAMS = {
}
OUTPUT_PATH = Path("raw/2025/football_data_org/leagues.json")
S3_KEY = "raw/2025/football_data_org/leagues.json"

S3_BUCKET = os.getenv("S3_BUCKET")

session = boto3.Session(
    profile_name=os.getenv("AWS_PROFILE"),
    region_name="ap-south-1",
)

s3_client = session.client("s3")
response = requests.request(
    method=METHOD,
    url=URL,
    headers=HEADERS,
    params=PARAMS,
)
response.raise_for_status()
data = response.json()
OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"Saved response to {OUTPUT_PATH.resolve()}")

body = json.dumps(data, indent=2, ensure_ascii=False).encode("utf-8")
s3_client.put_object(
    Bucket=S3_BUCKET,
    Key=S3_KEY,
    Body=body,
    ContentType="application/json",
)

print(f"Uploaded to s3://{S3_BUCKET}/{S3_KEY}")

Saved response to C:\Users\rahul\Documents\Projects\Football-data\raw\2025\football_data_org\leagues.json
Uploaded to s3://football-data-raw-01/raw/2025/football_data_org/leagues.json

Standings

In [2]:
import requests
import json
from pathlib import Path
import os
import boto3
from datetime import date
from dotenv import load_dotenv
load_dotenv()

# ---- Configure these ----
HEADERS = {
    "X-Auth-Token": os.getenv("FOOTBALL_DATA_ORG_API_KEY"),
}
S3_BUCKET = os.getenv("S3_BUCKET")
PROJECT_START_SEASON_YEAR = 2025

session = boto3.Session(
    profile_name=os.getenv("AWS_PROFILE"),
    region_name="ap-south-1",
)
s3_client = session.client("s3")

competition_resp = requests.get(
    "https://api.football-data.org/v4/competitions/PL",
    headers=HEADERS,
)
competition_resp.raise_for_status()
current_season = competition_resp.json()["currentSeason"]

start_date = date.fromisoformat(current_season["startDate"])
candidate_year = start_date.year
season_has_started = date.today() >= start_date

latest_active_year = candidate_year if season_has_started else candidate_year - 1
latest_active_year = max(latest_active_year, PROJECT_START_SEASON_YEAR)

SEASON_YEARS = list(range(PROJECT_START_SEASON_YEAR, latest_active_year + 1))
print(f"Active season years: {SEASON_YEARS}")

URL = "https://api.football-data.org/v4/competitions/PL/standings"
METHOD = "GET"

for season in SEASON_YEARS:
    PARAMS = {"season": season}
    OUTPUT_PATH = Path(f"raw/{season}/football_data_org/standings.json")
    S3_KEY = f"raw/{season}/football_data_org/standings.json"

    response = requests.request(
        method=METHOD,
        url=URL,
        headers=HEADERS,
        params=PARAMS,
    )
    response.raise_for_status()
    data = response.json()

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"Saved response to {OUTPUT_PATH.resolve()}")

    body = json.dumps(data, indent=2, ensure_ascii=False).encode("utf-8")
    s3_client.put_object(
        Bucket=S3_BUCKET,
        Key=S3_KEY,
        Body=body,
        ContentType="application/json",
    )
    print(f"Uploaded to s3://{S3_BUCKET}/{S3_KEY}")

Active season years: [2025, 2026]
Saved response to C:\Users\rahul\Documents\Projects\Football-data\raw\2025\football_data_org\standings.json
Uploaded to s3://football-data-raw-01/raw/2025/football_data_org/standings.json
Saved response to C:\Users\rahul\Documents\Projects\Football-data\raw\2026\football_data_org\standings.json
Uploaded to s3://football-data-raw-01/raw/2026/football_data_org/standings.json

Matches

In [3]:
import requests
import json
from pathlib import Path
import os
import boto3
from datetime import date
from dotenv import load_dotenv
load_dotenv()

HEADERS = {
    "X-Auth-Token": os.getenv("FOOTBALL_DATA_ORG_API_KEY"),
}
S3_BUCKET = os.getenv("S3_BUCKET")
PROJECT_START_SEASON_YEAR = 2025

session = boto3.Session(
    profile_name=os.getenv("AWS_PROFILE"),
    region_name="ap-south-1",
)
s3_client = session.client("s3")

competition_resp = requests.get(
    "https://api.football-data.org/v4/competitions/PL",
    headers=HEADERS,
)
competition_resp.raise_for_status()
current_season = competition_resp.json()["currentSeason"]

start_date = date.fromisoformat(current_season["startDate"])
candidate_year = start_date.year
season_has_started = date.today() >= start_date

latest_active_year = candidate_year if season_has_started else candidate_year - 1
latest_active_year = max(latest_active_year, PROJECT_START_SEASON_YEAR)

SEASON_YEARS = list(range(PROJECT_START_SEASON_YEAR, latest_active_year + 1))
print(f"Active season years: {SEASON_YEARS}")

URL = "https://api.football-data.org/v4/competitions/PL/matches"
METHOD = "GET"

for season in SEASON_YEARS:
    PARAMS = {"season": season}
    OUTPUT_PATH = Path(f"raw/{season}/football_data_org/matches.json")
    S3_KEY = f"raw/{season}/football_data_org/matches.json"

    response = requests.request(
        method=METHOD,
        url=URL,
        headers=HEADERS,
        params=PARAMS,
    )
    response.raise_for_status()
    data = response.json()

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"Saved response to {OUTPUT_PATH.resolve()}")

    body = json.dumps(data, indent=2, ensure_ascii=False).encode("utf-8")
    s3_client.put_object(
        Bucket=S3_BUCKET,
        Key=S3_KEY,
        Body=body,
        ContentType="application/json",
    )
    print(f"Uploaded to s3://{S3_BUCKET}/{S3_KEY}")

Active season years: [2025, 2026]
Saved response to C:\Users\rahul\Documents\Projects\Football-data\raw\2025\football_data_org\matches.json
Uploaded to s3://football-data-raw-01/raw/2025/football_data_org/matches.json
Saved response to C:\Users\rahul\Documents\Projects\Football-data\raw\2026\football_data_org\matches.json
Uploaded to s3://football-data-raw-01/raw/2026/football_data_org/matches.json

Teams

In [4]:
import requests
import json
from pathlib import Path
import os
import boto3
from datetime import date
from dotenv import load_dotenv
load_dotenv()

HEADERS = {
    "X-Auth-Token": os.getenv("FOOTBALL_DATA_ORG_API_KEY"),
}
S3_BUCKET = os.getenv("S3_BUCKET")
PROJECT_START_SEASON_YEAR = 2025

session = boto3.Session(
    profile_name=os.getenv("AWS_PROFILE"),
    region_name="ap-south-1",
)
s3_client = session.client("s3")

competition_resp = requests.get(
    "https://api.football-data.org/v4/competitions/PL",
    headers=HEADERS,
)
competition_resp.raise_for_status()
current_season = competition_resp.json()["currentSeason"]

start_date = date.fromisoformat(current_season["startDate"])
candidate_year = start_date.year
season_has_started = date.today() >= start_date

latest_active_year = candidate_year if season_has_started else candidate_year - 1
latest_active_year = max(latest_active_year, PROJECT_START_SEASON_YEAR)

SEASON_YEARS = list(range(PROJECT_START_SEASON_YEAR, latest_active_year + 1))
print(f"Active season years: {SEASON_YEARS}")

URL = "https://api.football-data.org/v4/competitions/PL/teams"
METHOD = "GET"

for season in SEASON_YEARS:
    PARAMS = {"season": season}
    OUTPUT_PATH = Path(f"raw/{season}/football_data_org/teams.json")
    S3_KEY = f"raw/{season}/football_data_org/teams.json"

    response = requests.request(
        method=METHOD,
        url=URL,
        headers=HEADERS,
        params=PARAMS,
    )
    response.raise_for_status()
    data = response.json()

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"Saved response to {OUTPUT_PATH.resolve()}")

    body = json.dumps(data, indent=2, ensure_ascii=False).encode("utf-8")
    s3_client.put_object(
        Bucket=S3_BUCKET,
        Key=S3_KEY,
        Body=body,
        ContentType="application/json",
    )
    print(f"Uploaded to s3://{S3_BUCKET}/{S3_KEY}")

Active season years: [2025, 2026]
Saved response to C:\Users\rahul\Documents\Projects\Football-data\raw\2025\football_data_org\teams.json
Uploaded to s3://football-data-raw-01/raw/2025/football_data_org/teams.json
Saved response to C:\Users\rahul\Documents\Projects\Football-data\raw\2026\football_data_org\teams.json
Uploaded to s3://football-data-raw-01/raw/2026/football_data_org/teams.json

SportsApiPro

Seasons

In [20]:
import requests
import json
from pathlib import Path
import os
import boto3
from dotenv import load_dotenv
load_dotenv()

# ---- Configure these ----
URL = "https://api.sportsapipro.com/v2/football/api/tournaments/17/seasons"
# ---- 17 is the tournament id for Premier League
METHOD = "GET"
HEADERS = {
    "x-api-key": os.getenv("API_FOOTBALL_KEY"),
}
PARAMS = {
}
OUTPUT_PATH = Path("raw/2025/sports_api_pro/seasons.json")
S3_BUCKET = os.getenv("S3_BUCKET")
S3_KEY = "raw/2025/sports_api_pro/seasons.json"

session = boto3.Session(
    profile_name=os.getenv("AWS_PROFILE"),
    region_name="ap-south-1",
)

s3_client = session.client("s3")
response = requests.request(
    method=METHOD,
    url=URL,
    headers=HEADERS,
    params=PARAMS,
)
response.raise_for_status()
data = response.json()
OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"Saved response to {OUTPUT_PATH.resolve()}")
body = json.dumps(data, indent=2, ensure_ascii=False).encode("utf-8")
s3_client.put_object(
    Bucket=S3_BUCKET,
    Key=S3_KEY,
    Body=body,
    ContentType="application/json",
)

print(f"Uploaded to s3://{S3_BUCKET}/{S3_KEY}")

Saved response to C:\Users\rahul\Documents\Projects\Football-data\raw\2025\sports_api_pro\seasons.json
Uploaded to s3://football-data-raw-01/raw/2025/sports_api_pro/seasons.json

Standings

In [17]:
import requests
import json
from pathlib import Path
import os
import boto3
from dotenv import load_dotenv
load_dotenv()

TOURNAMENT_ID = 17
PROJECT_START_SEASON_YEAR = 2025

HEADERS = {
    "x-api-key": os.getenv("API_FOOTBALL_KEY"),
}
S3_BUCKET = os.getenv("S3_BUCKET")

session = boto3.Session(
    profile_name=os.getenv("AWS_PROFILE"),
    region_name="ap-south-1",
)
s3_client = session.client("s3")


def parse_season_start_year(year_str):
    two_digit = int(year_str.split("/")[0])
    return 2000 + two_digit if two_digit < 50 else 1900 + two_digit


seasons_resp = requests.get(
    f"https://api.sportsapipro.com/v2/football/api/tournaments/{TOURNAMENT_ID}/seasons",
    headers=HEADERS,
)
seasons_resp.raise_for_status()
seasons = seasons_resp.json()["seasons"]

latest_season = seasons[0]
LATEST_FOLDER_YEAR = parse_season_start_year(latest_season["year"])

assert LATEST_FOLDER_YEAR >= PROJECT_START_SEASON_YEAR, (
    f"Resolved season year {LATEST_FOLDER_YEAR} is before project start "
    f"{PROJECT_START_SEASON_YEAR} — seasons[0] may not be the latest season, check API response."
)

relevant_seasons = [
    s for s in seasons
    if parse_season_start_year(s["year"]) >= PROJECT_START_SEASON_YEAR
]

URL_TEMPLATE = f"https://api.sportsapipro.com/v2/football/tournament/{TOURNAMENT_ID}/season/{{season_id}}/standings"
METHOD = "GET"
PARAMS = {}

for season in relevant_seasons:
    SEASON_ID = season["id"]
    FOLDER_YEAR = parse_season_start_year(season["year"])
    is_latest = FOLDER_YEAR == LATEST_FOLDER_YEAR

    OUTPUT_PATH = Path(f"raw/{FOLDER_YEAR}/sports_api_pro/standings.json")
    S3_KEY = f"raw/{FOLDER_YEAR}/sports_api_pro/standings.json"

    # Finished seasons don't need refetching once loaded - only the live season changes.
    if not is_latest and OUTPUT_PATH.exists():
        print(f"Skipping {FOLDER_YEAR} (season {SEASON_ID}) - already saved locally.")
        continue

    URL = URL_TEMPLATE.format(season_id=SEASON_ID)
    response = requests.request(method=METHOD, url=URL, headers=HEADERS, params=PARAMS)
    response.raise_for_status()
    data = response.json()

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    print(f"Saved response to {OUTPUT_PATH.resolve()}")

    body = json.dumps(data, indent=2, ensure_ascii=False).encode("utf-8")
    s3_client.put_object(
        Bucket=S3_BUCKET,
        Key=S3_KEY,
        Body=body,
        ContentType="application/json",
    )
    print(f"Uploaded to s3://{S3_BUCKET}/{S3_KEY}")

Saved response to C:\Users\rahul\Documents\Projects\Football-data\raw\2026\sports_api_pro\standings.json
Uploaded to s3://football-data-raw-01/raw/2026/sports_api_pro/standings.json
Skipping 2025 (season 76986) - already saved locally.

All Matches

In [ ]:
import requests
import json
import time
from pathlib import Path
import os
import boto3
from dotenv import load_dotenv
load_dotenv()

TOURNAMENT_ID = 17
PROJECT_START_SEASON_YEAR = 2025
SLEEP_SECONDS = 7
MAX_EVENT_PAGES = 13

HEADERS = {
    "x-api-key": os.getenv("API_FOOTBALL_KEY"),
}
S3_BUCKET = os.getenv("S3_BUCKET")

session = boto3.Session(
    profile_name=os.getenv("AWS_PROFILE"),
    region_name="ap-south-1",
)
s3_client = session.client("s3")


def parse_season_start_year(year_str):
    # "26/27" -> 2026, "99/00" -> 1999, "92/93" -> 1992
    two_digit = int(year_str.split("/")[0])
    return 2000 + two_digit if two_digit < 50 else 1900 + two_digit


seasons_resp = requests.get(
    f"https://api.sportsapipro.com/v2/football/api/tournaments/{TOURNAMENT_ID}/seasons",
    headers=HEADERS,
)
seasons_resp.raise_for_status()
seasons = seasons_resp.json()["seasons"]

latest_season = seasons[0]
LATEST_FOLDER_YEAR = parse_season_start_year(latest_season["year"])

assert LATEST_FOLDER_YEAR >= PROJECT_START_SEASON_YEAR, (
    f"Resolved season year {LATEST_FOLDER_YEAR} is before project start "
    f"{PROJECT_START_SEASON_YEAR} — seasons[0] may not be the latest season, check API response."
)

relevant_seasons = [
    s for s in seasons
    if parse_season_start_year(s["year"]) >= PROJECT_START_SEASON_YEAR
]

URL_TEMPLATE = f"https://api.sportsapipro.com/v2/football/tournament/{TOURNAMENT_ID}/season/{{season_id}}/events/last/{{event}}"
METHOD = "GET"
PARAMS = {}

for season in relevant_seasons:
    SEASON_ID = season["id"]
    FOLDER_YEAR = parse_season_start_year(season["year"])
    is_latest = FOLDER_YEAR == LATEST_FOLDER_YEAR
    DONE_MARKER_PATH = Path(f"raw/{FOLDER_YEAR}/sports_api_pro/_events_complete")

    if not is_latest and DONE_MARKER_PATH.exists():
        print(f"Skipping {FOLDER_YEAR} (season {SEASON_ID}) - events already backfilled locally.")
        continue

    print(f"Processing events for {FOLDER_YEAR} (season {SEASON_ID})...")
    reached_end = False

    for event in range(MAX_EVENT_PAGES):
        OUTPUT_PATH = Path(f"raw/{FOLDER_YEAR}/sports_api_pro/events_{event}.json")
        S3_KEY = f"raw/{FOLDER_YEAR}/sports_api_pro/events_{event}.json"

        # Skip pages already saved locally (finished seasons only - live season always refreshes).
        if not is_latest and OUTPUT_PATH.exists():
            print(f"Skipping event={event} for {FOLDER_YEAR} - file already exists locally.")
            continue

        URL = URL_TEMPLATE.format(season_id=SEASON_ID, event=event)
        response = requests.request(method=METHOD, url=URL, headers=HEADERS, params=PARAMS)

        if response.status_code == 404:
            print(f"Got 404 at event={event}, no more pages for {FOLDER_YEAR}.")
            reached_end = True
            break

        response.raise_for_status()
        data = response.json()

        OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
        with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
        print(f"Saved response to {OUTPUT_PATH.resolve()}")

        body = json.dumps(data, indent=2, ensure_ascii=False).encode("utf-8")
        s3_client.put_object(
            Bucket=S3_BUCKET,
            Key=S3_KEY,
            Body=body,
            ContentType="application/json",
        )
        print(f"Uploaded to s3://{S3_BUCKET}/{S3_KEY}")

        time.sleep(SLEEP_SECONDS)
    else:
        print(f"Reached MAX_EVENT_PAGES={MAX_EVENT_PAGES} for {FOLDER_YEAR} without a 404 - check manually.")

    if not is_latest and reached_end:
        DONE_MARKER_PATH.parent.mkdir(parents=True, exist_ok=True)
        DONE_MARKER_PATH.write_text("")
        print(f"Marked {FOLDER_YEAR} as complete -> {DONE_MARKER_PATH}")

Processing events for 2026 (season 96668)...
Saved response to C:\Users\rahul\Documents\Projects\Football-data\raw\2026\sports_api_pro\events_0.json
Uploaded to s3://football-data-raw-01/raw/2026/sports_api_pro/events_0.json
Got 404 at event=1, no more pages for 2026.
Processing events for 2025 (season 76986)...
Skipping event=0 for 2025 - file already exists locally.
Skipping event=1 for 2025 - file already exists locally.
Skipping event=2 for 2025 - file already exists locally.
Skipping event=3 for 2025 - file already exists locally.
Skipping event=4 for 2025 - file already exists locally.
Skipping event=5 for 2025 - file already exists locally.
Skipping event=6 for 2025 - file already exists locally.
Skipping event=7 for 2025 - file already exists locally.
Skipping event=8 for 2025 - file already exists locally.
Skipping event=9 for 2025 - file already exists locally.
Skipping event=10 for 2025 - file already exists locally.
Skipping event=11 for 2025 - file already exists locally.
Skipping event=12 for 2025 - file already exists locally.
Reached MAX_EVENT_PAGES=13 for 2025 without a 404 - check manually.

SoccerData-FBRef

Players Season Stats - Standard

In [22]:
import requests
import soccerdata as sd
from pathlib import Path
import os
import boto3
from datetime import date
from dotenv import load_dotenv
load_dotenv()

HEADERS = {
    "X-Auth-Token": os.getenv("FOOTBALL_DATA_ORG_API_KEY"),
}
S3_BUCKET = os.getenv("S3_BUCKET")
PROJECT_START_SEASON_YEAR = 2025

session = boto3.Session(
    profile_name=os.getenv("AWS_PROFILE"),
    region_name="ap-south-1",
)
s3_client = session.client("s3")

competition_resp = requests.get(
    "https://api.football-data.org/v4/competitions/PL",
    headers=HEADERS,
)
competition_resp.raise_for_status()
current_season = competition_resp.json()["currentSeason"]

start_date = date.fromisoformat(current_season["startDate"])
candidate_year = start_date.year
season_has_started = date.today() >= start_date

latest_active_year = candidate_year if season_has_started else candidate_year - 1
LATEST_SEASON_YEAR = max(latest_active_year, PROJECT_START_SEASON_YEAR)

SEASON_YEARS = list(range(PROJECT_START_SEASON_YEAR, LATEST_SEASON_YEAR + 1))
print(f"Relevant season years: {SEASON_YEARS}")

for season_year in SEASON_YEARS:
    is_latest = season_year == LATEST_SEASON_YEAR

    OUTPUT_PATH = Path(f"raw/{season_year}/soccerdata_fbref/players_season_standard_stats.csv")
    S3_KEY = f"raw/{season_year}/soccerdata_fbref/players_season_standard_stats.csv"

    # Finished seasons don't need refetching once loaded - only the live season changes.
    if not is_latest and OUTPUT_PATH.exists():
        print(f"Skipping {season_year} - already saved locally.")
        continue

    print(f"Fetching standard stats for {season_year}...")
    fbref = sd.FBref(leagues="ENG-Premier League", seasons=season_year)
    players_df = fbref.read_player_season_stats(stat_type="standard")
    players_df = players_df.reset_index()

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    players_df.to_csv(OUTPUT_PATH, index=False)
    print(f"Saved response to {OUTPUT_PATH.resolve()}")

    body = players_df.to_csv(index=False).encode("utf-8")
    s3_client.put_object(
        Bucket=S3_BUCKET,
        Key=S3_KEY,
        Body=body,
        ContentType="text/csv",
    )
    print(f"Uploaded to s3://{S3_BUCKET}/{S3_KEY}")

Relevant season years: [2025, 2026]
Skipping 2025 - already saved locally.
Fetching standard stats for 2026...

[08/28/26 14:36:22] INFO     Saving cached data to C:\Users\rahul\soccerdata\data\FBref              ]8;id=7009565;file://c:\Users\rahul\.pyenv\pyenv-win\versions\3.11.5\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=7009566;file://c:\Users\rahul\.pyenv\pyenv-win\versions\3.11.5\Lib\site-packages\soccerdata\_common.py#250\250]8;;\

Saved response to C:\Users\rahul\Documents\Projects\Football-data\raw\2026\soccerdata_fbref\players_season_standard_stats.csv

[08/28/26 14:36:38] INFO     Loading cached SSO token for football-data-sso                           ]8;id=7009571;file://c:\Users\rahul\.pyenv\pyenv-win\versions\3.11.5\Lib\site-packages\botocore\tokens.py\tokens.py]8;;\:]8;id=7009572;file://c:\Users\rahul\.pyenv\pyenv-win\versions\3.11.5\Lib\site-packages\botocore\tokens.py#377\377]8;;\

Uploaded to s3://football-data-raw-01/raw/2026/soccerdata_fbref/players_season_standard_stats.csv

Players Season Stats - Shooting

In [ ]:
import requests
import soccerdata as sd
from pathlib import Path
import os
import boto3
from datetime import date
from dotenv import load_dotenv
load_dotenv()

HEADERS = {
    "X-Auth-Token": os.getenv("FOOTBALL_DATA_ORG_API_KEY"),
}
S3_BUCKET = os.getenv("S3_BUCKET")
PROJECT_START_SEASON_YEAR = 2025

session = boto3.Session(
    profile_name=os.getenv("AWS_PROFILE"),
    region_name="ap-south-1",
)
s3_client = session.client("s3")

competition_resp = requests.get(
    "https://api.football-data.org/v4/competitions/PL",
    headers=HEADERS,
)
competition_resp.raise_for_status()
current_season = competition_resp.json()["currentSeason"]

start_date = date.fromisoformat(current_season["startDate"])
candidate_year = start_date.year
season_has_started = date.today() >= start_date

latest_active_year = candidate_year if season_has_started else candidate_year - 1
LATEST_SEASON_YEAR = max(latest_active_year, PROJECT_START_SEASON_YEAR)

SEASON_YEARS = list(range(PROJECT_START_SEASON_YEAR, LATEST_SEASON_YEAR + 1))
print(f"Relevant season years: {SEASON_YEARS}")

for season_year in SEASON_YEARS:
    is_latest = season_year == LATEST_SEASON_YEAR

    OUTPUT_PATH = Path(f"raw/{season_year}/soccerdata_fbref/players_season_shooting_stats.csv")
    S3_KEY = f"raw/{season_year}/soccerdata_fbref/players_season_shooting_stats.csv"

    if not is_latest and OUTPUT_PATH.exists():
        print(f"Skipping {season_year} - already saved locally.")
        continue

    print(f"Fetching shooting stats for {season_year}...")
    fbref = sd.FBref(leagues="ENG-Premier League", seasons=season_year)
    players_df = fbref.read_player_season_stats(stat_type="shooting")
    players_df = players_df.reset_index()

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    players_df.to_csv(OUTPUT_PATH, index=False)
    print(f"Saved response to {OUTPUT_PATH.resolve()}")

    body = players_df.to_csv(index=False).encode("utf-8")
    s3_client.put_object(
        Bucket=S3_BUCKET,
        Key=S3_KEY,
        Body=body,
        ContentType="text/csv",
    )
    print(f"Uploaded to s3://{S3_BUCKET}/{S3_KEY}")

Relevant season years: [2025, 2026]
Skipping 2025 - already saved locally.
Fetching shooting stats for 2026...

[08/28/26 14:35:09] INFO     Saving cached data to C:\Users\rahul\soccerdata\data\FBref              ]8;id=7009544;file://c:\Users\rahul\.pyenv\pyenv-win\versions\3.11.5\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=7009545;file://c:\Users\rahul\.pyenv\pyenv-win\versions\3.11.5\Lib\site-packages\soccerdata\_common.py#250\250]8;;\

Saved response to C:\Users\rahul\Documents\Projects\Football-data\raw\2026\soccerdata_fbref\players_season_shooting_stats.csv

[08/28/26 14:35:11] INFO     Loading cached SSO token for football-data-sso                           ]8;id=7009552;file://c:\Users\rahul\.pyenv\pyenv-win\versions\3.11.5\Lib\site-packages\botocore\tokens.py\tokens.py]8;;\:]8;id=7009553;file://c:\Users\rahul\.pyenv\pyenv-win\versions\3.11.5\Lib\site-packages\botocore\tokens.py#377\377]8;;\

                    INFO     SSO Token refresh succeeded                                              ]8;id=7009559;file://c:\Users\rahul\.pyenv\pyenv-win\versions\3.11.5\Lib\site-packages\botocore\tokens.py\tokens.py]8;;\:]8;id=7009560;file://c:\Users\rahul\.pyenv\pyenv-win\versions\3.11.5\Lib\site-packages\botocore\tokens.py#347\347]8;;\

Uploaded to s3://football-data-raw-01/raw/2026/soccerdata_fbref/players_season_shooting_stats.csv

Players Season Stats - Playing Time

In [23]:
import requests
import soccerdata as sd
from pathlib import Path
import os
import boto3
from datetime import date
from dotenv import load_dotenv
load_dotenv()

HEADERS = {
    "X-Auth-Token": os.getenv("FOOTBALL_DATA_ORG_API_KEY"),
}
S3_BUCKET = os.getenv("S3_BUCKET")
PROJECT_START_SEASON_YEAR = 2025

session = boto3.Session(
    profile_name=os.getenv("AWS_PROFILE"),
    region_name="ap-south-1",
)
s3_client = session.client("s3")

competition_resp = requests.get(
    "https://api.football-data.org/v4/competitions/PL",
    headers=HEADERS,
)
competition_resp.raise_for_status()
current_season = competition_resp.json()["currentSeason"]

start_date = date.fromisoformat(current_season["startDate"])
candidate_year = start_date.year
season_has_started = date.today() >= start_date

latest_active_year = candidate_year if season_has_started else candidate_year - 1
LATEST_SEASON_YEAR = max(latest_active_year, PROJECT_START_SEASON_YEAR)

SEASON_YEARS = list(range(PROJECT_START_SEASON_YEAR, LATEST_SEASON_YEAR + 1))
print(f"Relevant season years: {SEASON_YEARS}")

for season_year in SEASON_YEARS:
    is_latest = season_year == LATEST_SEASON_YEAR

    OUTPUT_PATH = Path(f"raw/{season_year}/soccerdata_fbref/players_season_playing_time_stats.csv")
    S3_KEY = f"raw/{season_year}/soccerdata_fbref/players_season_playing_time_stats.csv"

    if not is_latest and OUTPUT_PATH.exists():
        print(f"Skipping {season_year} - already saved locally.")
        continue

    print(f"Fetching playing_time stats for {season_year}...")
    fbref = sd.FBref(leagues="ENG-Premier League", seasons=season_year)
    players_df = fbref.read_player_season_stats(stat_type="playing_time")
    players_df = players_df.reset_index()

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    players_df.to_csv(OUTPUT_PATH, index=False)
    print(f"Saved response to {OUTPUT_PATH.resolve()}")

    body = players_df.to_csv(index=False).encode("utf-8")
    s3_client.put_object(
        Bucket=S3_BUCKET,
        Key=S3_KEY,
        Body=body,
        ContentType="text/csv",
    )
    print(f"Uploaded to s3://{S3_BUCKET}/{S3_KEY}")

Relevant season years: [2025, 2026]
Skipping 2025 - already saved locally.
Fetching playing_time stats for 2026...

[08/28/26 14:37:43] INFO     Saving cached data to C:\Users\rahul\soccerdata\data\FBref              ]8;id=7009577;file://c:\Users\rahul\.pyenv\pyenv-win\versions\3.11.5\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=7009578;file://c:\Users\rahul\.pyenv\pyenv-win\versions\3.11.5\Lib\site-packages\soccerdata\_common.py#250\250]8;;\

Saved response to C:\Users\rahul\Documents\Projects\Football-data\raw\2026\soccerdata_fbref\players_season_playing_time_stats.csv

[08/28/26 14:42:47] INFO     Loading cached SSO token for football-data-sso                           ]8;id=7009583;file://c:\Users\rahul\.pyenv\pyenv-win\versions\3.11.5\Lib\site-packages\botocore\tokens.py\tokens.py]8;;\:]8;id=7009584;file://c:\Users\rahul\.pyenv\pyenv-win\versions\3.11.5\Lib\site-packages\botocore\tokens.py#377\377]8;;\

Uploaded to s3://football-data-raw-01/raw/2026/soccerdata_fbref/players_season_playing_time_stats.csv

Players Season Stats - Keeper

In [24]:
import requests
import soccerdata as sd
from pathlib import Path
import os
import boto3
from datetime import date
from dotenv import load_dotenv
load_dotenv()

HEADERS = {
    "X-Auth-Token": os.getenv("FOOTBALL_DATA_ORG_API_KEY"),
}
S3_BUCKET = os.getenv("S3_BUCKET")
PROJECT_START_SEASON_YEAR = 2025

session = boto3.Session(
    profile_name=os.getenv("AWS_PROFILE"),
    region_name="ap-south-1",
)
s3_client = session.client("s3")

competition_resp = requests.get(
    "https://api.football-data.org/v4/competitions/PL",
    headers=HEADERS,
)
competition_resp.raise_for_status()
current_season = competition_resp.json()["currentSeason"]

start_date = date.fromisoformat(current_season["startDate"])
candidate_year = start_date.year
season_has_started = date.today() >= start_date

latest_active_year = candidate_year if season_has_started else candidate_year - 1
LATEST_SEASON_YEAR = max(latest_active_year, PROJECT_START_SEASON_YEAR)

SEASON_YEARS = list(range(PROJECT_START_SEASON_YEAR, LATEST_SEASON_YEAR + 1))
print(f"Relevant season years: {SEASON_YEARS}")

for season_year in SEASON_YEARS:
    is_latest = season_year == LATEST_SEASON_YEAR

    OUTPUT_PATH = Path(f"raw/{season_year}/soccerdata_fbref/players_season_keeper_stats.csv")
    S3_KEY = f"raw/{season_year}/soccerdata_fbref/players_season_keeper_stats.csv"

    if not is_latest and OUTPUT_PATH.exists():
        print(f"Skipping {season_year} - already saved locally.")
        continue

    print(f"Fetching keeper stats for {season_year}...")
    fbref = sd.FBref(leagues="ENG-Premier League", seasons=season_year)
    players_df = fbref.read_player_season_stats(stat_type="keeper")
    players_df = players_df.reset_index()

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    players_df.to_csv(OUTPUT_PATH, index=False)
    print(f"Saved response to {OUTPUT_PATH.resolve()}")

    body = players_df.to_csv(index=False).encode("utf-8")
    s3_client.put_object(
        Bucket=S3_BUCKET,
        Key=S3_KEY,
        Body=body,
        ContentType="text/csv",
    )
    print(f"Uploaded to s3://{S3_BUCKET}/{S3_KEY}")

Relevant season years: [2025, 2026]
Skipping 2025 - already saved locally.
Fetching keeper stats for 2026...

[08/28/26 14:43:52] INFO     Saving cached data to C:\Users\rahul\soccerdata\data\FBref              ]8;id=7009589;file://c:\Users\rahul\.pyenv\pyenv-win\versions\3.11.5\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=7009590;file://c:\Users\rahul\.pyenv\pyenv-win\versions\3.11.5\Lib\site-packages\soccerdata\_common.py#250\250]8;;\

Saved response to C:\Users\rahul\Documents\Projects\Football-data\raw\2026\soccerdata_fbref\players_season_keeper_stats.csv

[08/28/26 14:48:09] INFO     Loading cached SSO token for football-data-sso                           ]8;id=7009595;file://c:\Users\rahul\.pyenv\pyenv-win\versions\3.11.5\Lib\site-packages\botocore\tokens.py\tokens.py]8;;\:]8;id=7009596;file://c:\Users\rahul\.pyenv\pyenv-win\versions\3.11.5\Lib\site-packages\botocore\tokens.py#377\377]8;;\

Uploaded to s3://football-data-raw-01/raw/2026/soccerdata_fbref/players_season_keeper_stats.csv

Players Season Stats - Misc

In [25]:
import requests
import soccerdata as sd
from pathlib import Path
import os
import boto3
from datetime import date
from dotenv import load_dotenv
load_dotenv()

HEADERS = {
    "X-Auth-Token": os.getenv("FOOTBALL_DATA_ORG_API_KEY"),
}
S3_BUCKET = os.getenv("S3_BUCKET")
PROJECT_START_SEASON_YEAR = 2025

session = boto3.Session(
    profile_name=os.getenv("AWS_PROFILE"),
    region_name="ap-south-1",
)
s3_client = session.client("s3")

competition_resp = requests.get(
    "https://api.football-data.org/v4/competitions/PL",
    headers=HEADERS,
)
competition_resp.raise_for_status()
current_season = competition_resp.json()["currentSeason"]

start_date = date.fromisoformat(current_season["startDate"])
candidate_year = start_date.year
season_has_started = date.today() >= start_date

latest_active_year = candidate_year if season_has_started else candidate_year - 1
LATEST_SEASON_YEAR = max(latest_active_year, PROJECT_START_SEASON_YEAR)

SEASON_YEARS = list(range(PROJECT_START_SEASON_YEAR, LATEST_SEASON_YEAR + 1))
print(f"Relevant season years: {SEASON_YEARS}")

for season_year in SEASON_YEARS:
    is_latest = season_year == LATEST_SEASON_YEAR

    OUTPUT_PATH = Path(f"raw/{season_year}/soccerdata_fbref/players_season_misc_stats.csv")
    S3_KEY = f"raw/{season_year}/soccerdata_fbref/players_season_misc_stats.csv"

    if not is_latest and OUTPUT_PATH.exists():
        print(f"Skipping {season_year} - already saved locally.")
        continue

    print(f"Fetching misc stats for {season_year}...")
    fbref = sd.FBref(leagues="ENG-Premier League", seasons=season_year)
    players_df = fbref.read_player_season_stats(stat_type="misc")
    players_df = players_df.reset_index()

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    players_df.to_csv(OUTPUT_PATH, index=False)
    print(f"Saved response to {OUTPUT_PATH.resolve()}")

    body = players_df.to_csv(index=False).encode("utf-8")
    s3_client.put_object(
        Bucket=S3_BUCKET,
        Key=S3_KEY,
        Body=body,
        ContentType="text/csv",
    )
    print(f"Uploaded to s3://{S3_BUCKET}/{S3_KEY}")

Relevant season years: [2025, 2026]
Skipping 2025 - already saved locally.
Fetching misc stats for 2026...

[08/28/26 14:48:24] INFO     Saving cached data to C:\Users\rahul\soccerdata\data\FBref              ]8;id=7009601;file://c:\Users\rahul\.pyenv\pyenv-win\versions\3.11.5\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=7009602;file://c:\Users\rahul\.pyenv\pyenv-win\versions\3.11.5\Lib\site-packages\soccerdata\_common.py#250\250]8;;\

Saved response to C:\Users\rahul\Documents\Projects\Football-data\raw\2026\soccerdata_fbref\players_season_misc_stats.csv

[08/28/26 14:48:40] INFO     Loading cached SSO token for football-data-sso                           ]8;id=7009607;file://c:\Users\rahul\.pyenv\pyenv-win\versions\3.11.5\Lib\site-packages\botocore\tokens.py\tokens.py]8;;\:]8;id=7009608;file://c:\Users\rahul\.pyenv\pyenv-win\versions\3.11.5\Lib\site-packages\botocore\tokens.py#377\377]8;;\

Uploaded to s3://football-data-raw-01/raw/2026/soccerdata_fbref/players_season_misc_stats.csv

Schedule

In [26]:
import requests
import soccerdata as sd
from pathlib import Path
import os
import boto3
from datetime import date
from dotenv import load_dotenv
load_dotenv()

HEADERS = {
    "X-Auth-Token": os.getenv("FOOTBALL_DATA_ORG_API_KEY"),
}
S3_BUCKET = os.getenv("S3_BUCKET")
PROJECT_START_SEASON_YEAR = 2025

session = boto3.Session(
    profile_name=os.getenv("AWS_PROFILE"),
    region_name="ap-south-1",
)
s3_client = session.client("s3")

competition_resp = requests.get(
    "https://api.football-data.org/v4/competitions/PL",
    headers=HEADERS,
)
competition_resp.raise_for_status()
current_season = competition_resp.json()["currentSeason"]

start_date = date.fromisoformat(current_season["startDate"])
candidate_year = start_date.year
season_has_started = date.today() >= start_date

latest_active_year = candidate_year if season_has_started else candidate_year - 1
LATEST_SEASON_YEAR = max(latest_active_year, PROJECT_START_SEASON_YEAR)

SEASON_YEARS = list(range(PROJECT_START_SEASON_YEAR, LATEST_SEASON_YEAR + 1))
print(f"Relevant season years: {SEASON_YEARS}")

for season_year in SEASON_YEARS:
    is_latest = season_year == LATEST_SEASON_YEAR

    OUTPUT_PATH = Path(f"raw/{season_year}/soccerdata_fbref/schedule.csv")
    S3_KEY = f"raw/{season_year}/soccerdata_fbref/schedule.csv"

    if not is_latest and OUTPUT_PATH.exists():
        print(f"Skipping {season_year} - already saved locally.")
        continue

    print(f"Fetching schedule for {season_year}...")
    fbref = sd.FBref(leagues="ENG-Premier League", seasons=season_year)
    schedule_df = fbref.read_schedule()
    schedule_df = schedule_df.reset_index()

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    schedule_df.to_csv(OUTPUT_PATH, index=False)
    print(f"Saved response to {OUTPUT_PATH.resolve()}")

    body = schedule_df.to_csv(index=False).encode("utf-8")
    s3_client.put_object(
        Bucket=S3_BUCKET,
        Key=S3_KEY,
        Body=body,
        ContentType="text/csv",
    )
    print(f"Uploaded to s3://{S3_BUCKET}/{S3_KEY}")

Relevant season years: [2025, 2026]
Skipping 2025 - already saved locally.
Fetching schedule for 2026...

[08/28/26 14:49:52] INFO     Saving cached data to C:\Users\rahul\soccerdata\data\FBref              ]8;id=7009613;file://c:\Users\rahul\.pyenv\pyenv-win\versions\3.11.5\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=7009614;file://c:\Users\rahul\.pyenv\pyenv-win\versions\3.11.5\Lib\site-packages\soccerdata\_common.py#250\250]8;;\

Saved response to C:\Users\rahul\Documents\Projects\Football-data\raw\2026\soccerdata_fbref\schedule.csv

[08/28/26 14:56:31] INFO     Loading cached SSO token for football-data-sso                           ]8;id=7009619;file://c:\Users\rahul\.pyenv\pyenv-win\versions\3.11.5\Lib\site-packages\botocore\tokens.py\tokens.py]8;;\:]8;id=7009620;file://c:\Users\rahul\.pyenv\pyenv-win\versions\3.11.5\Lib\site-packages\botocore\tokens.py#377\377]8;;\

Uploaded to s3://football-data-raw-01/raw/2026/soccerdata_fbref/schedule.csv

Lineups

In [ ]:
import requests
import soccerdata as sd
from pathlib import Path
import os
import boto3
from datetime import date
from dotenv import load_dotenv
load_dotenv()

HEADERS = {
    "X-Auth-Token": os.getenv("FOOTBALL_DATA_ORG_API_KEY"),
}
S3_BUCKET = os.getenv("S3_BUCKET")
PROJECT_START_SEASON_YEAR = 2025

session = boto3.Session(
    profile_name=os.getenv("AWS_PROFILE"),
    region_name="ap-south-1",
)
s3_client = session.client("s3")

competition_resp = requests.get(
    "https://api.football-data.org/v4/competitions/PL",
    headers=HEADERS,
)
competition_resp.raise_for_status()
current_season = competition_resp.json()["currentSeason"]

start_date = date.fromisoformat(current_season["startDate"])
candidate_year = start_date.year
season_has_started = date.today() >= start_date

latest_active_year = candidate_year if season_has_started else candidate_year - 1
LATEST_SEASON_YEAR = max(latest_active_year, PROJECT_START_SEASON_YEAR)

SEASON_YEARS = list(range(PROJECT_START_SEASON_YEAR, LATEST_SEASON_YEAR + 1))
print(f"Relevant season years: {SEASON_YEARS}")

for season_year in SEASON_YEARS:
    is_latest = season_year == LATEST_SEASON_YEAR

    OUTPUT_PATH = Path(f"raw/{season_year}/soccerdata_fbref/lineup.csv")
    S3_KEY = f"raw/{season_year}/soccerdata_fbref/lineup.csv"

    if not is_latest and OUTPUT_PATH.exists():
        print(f"Skipping {season_year} - already saved locally.")
        continue

    print(f"Fetching lineup for {season_year}...")
    fbref = sd.FBref(leagues="ENG-Premier League", seasons=season_year)
    lineup_df = fbref.read_lineup()
    lineup_df = lineup_df.reset_index()

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    lineup_df.to_csv(OUTPUT_PATH, index=False)
    print(f"Saved response to {OUTPUT_PATH.resolve()}")

    body = lineup_df.to_csv(index=False).encode("utf-8")
    s3_client.put_object(
        Bucket=S3_BUCKET,
        Key=S3_KEY,
        Body=body,
        ContentType="text/csv",
    )
    print(f"Uploaded to s3://{S3_BUCKET}/{S3_KEY}")

Events

In [ ]:
import requests
import soccerdata as sd
from pathlib import Path
import os
import boto3
from datetime import date
from dotenv import load_dotenv
load_dotenv()

HEADERS = {
    "X-Auth-Token": os.getenv("FOOTBALL_DATA_ORG_API_KEY"),
}
S3_BUCKET = os.getenv("S3_BUCKET")
PROJECT_START_SEASON_YEAR = 2025

session = boto3.Session(
    profile_name=os.getenv("AWS_PROFILE"),
    region_name="ap-south-1",
)
s3_client = session.client("s3")

competition_resp = requests.get(
    "https://api.football-data.org/v4/competitions/PL",
    headers=HEADERS,
)
competition_resp.raise_for_status()
current_season = competition_resp.json()["currentSeason"]

start_date = date.fromisoformat(current_season["startDate"])
candidate_year = start_date.year
season_has_started = date.today() >= start_date

latest_active_year = candidate_year if season_has_started else candidate_year - 1
LATEST_SEASON_YEAR = max(latest_active_year, PROJECT_START_SEASON_YEAR)

SEASON_YEARS = list(range(PROJECT_START_SEASON_YEAR, LATEST_SEASON_YEAR + 1))
print(f"Relevant season years: {SEASON_YEARS}")

for season_year in SEASON_YEARS:
    is_latest = season_year == LATEST_SEASON_YEAR

    OUTPUT_PATH = Path(f"raw/{season_year}/soccerdata_fbref/events.csv")
    S3_KEY = f"raw/{season_year}/soccerdata_fbref/events.csv"

    if not is_latest and OUTPUT_PATH.exists():
        print(f"Skipping {season_year} - already saved locally.")
        continue

    print(f"Fetching events for {season_year}...")
    fbref = sd.FBref(leagues="ENG-Premier League", seasons=season_year)
    events_df = fbref.read_events()
    events_df = events_df.reset_index()

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    events_df.to_csv(OUTPUT_PATH, index=False)
    print(f"Saved response to {OUTPUT_PATH.resolve()}")

    body = events_df.to_csv(index=False).encode("utf-8")
    s3_client.put_object(
        Bucket=S3_BUCKET,
        Key=S3_KEY,
        Body=body,
        ContentType="text/csv",
    )
    print(f"Uploaded to s3://{S3_BUCKET}/{S3_KEY}")

Player Match Stats

In [ ]:
import requests
import soccerdata as sd
from pathlib import Path
import os
import boto3
from datetime import date
from dotenv import load_dotenv
load_dotenv()

HEADERS = {
    "X-Auth-Token": os.getenv("FOOTBALL_DATA_ORG_API_KEY"),
}
S3_BUCKET = os.getenv("S3_BUCKET")
PROJECT_START_SEASON_YEAR = 2025

session = boto3.Session(
    profile_name=os.getenv("AWS_PROFILE"),
    region_name="ap-south-1",
)
s3_client = session.client("s3")

competition_resp = requests.get(
    "https://api.football-data.org/v4/competitions/PL",
    headers=HEADERS,
)
competition_resp.raise_for_status()
current_season = competition_resp.json()["currentSeason"]

start_date = date.fromisoformat(current_season["startDate"])
candidate_year = start_date.year
season_has_started = date.today() >= start_date

latest_active_year = candidate_year if season_has_started else candidate_year - 1
LATEST_SEASON_YEAR = max(latest_active_year, PROJECT_START_SEASON_YEAR)

SEASON_YEARS = list(range(PROJECT_START_SEASON_YEAR, LATEST_SEASON_YEAR + 1))
print(f"Relevant season years: {SEASON_YEARS}")

for season_year in SEASON_YEARS:
    is_latest = season_year == LATEST_SEASON_YEAR

    OUTPUT_PATH = Path(f"raw/{season_year}/soccerdata_fbref/player_match_stats_summary.csv")
    S3_KEY = f"raw/{season_year}/soccerdata_fbref/player_match_stats_summary.csv"

    if not is_latest and OUTPUT_PATH.exists():
        print(f"Skipping {season_year} - already saved locally.")
        continue

    print(f"Fetching player match stats (summary) for {season_year}...")
    fbref = sd.FBref(leagues="ENG-Premier League", seasons=season_year)
    player_match_df = fbref.read_player_match_stats(stat_type='summary')
    player_match_df = player_match_df.reset_index()

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    player_match_df.to_csv(OUTPUT_PATH, index=False)
    print(f"Saved response to {OUTPUT_PATH.resolve()}")

    body = player_match_df.to_csv(index=False).encode("utf-8")
    s3_client.put_object(
        Bucket=S3_BUCKET,
        Key=S3_KEY,
        Body=body,
        ContentType="text/csv",
    )
    print(f"Uploaded to s3://{S3_BUCKET}/{S3_KEY}")

Player Match Stats Goalkeeper

In [ ]:
import requests
import soccerdata as sd
from pathlib import Path
import os
import boto3
from datetime import date
from dotenv import load_dotenv
load_dotenv()

HEADERS = {
    "X-Auth-Token": os.getenv("FOOTBALL_DATA_ORG_API_KEY"),
}
S3_BUCKET = os.getenv("S3_BUCKET")
PROJECT_START_SEASON_YEAR = 2025

session = boto3.Session(
    profile_name=os.getenv("AWS_PROFILE"),
    region_name="ap-south-1",
)
s3_client = session.client("s3")

competition_resp = requests.get(
    "https://api.football-data.org/v4/competitions/PL",
    headers=HEADERS,
)
competition_resp.raise_for_status()
current_season = competition_resp.json()["currentSeason"]

start_date = date.fromisoformat(current_season["startDate"])
candidate_year = start_date.year
season_has_started = date.today() >= start_date

latest_active_year = candidate_year if season_has_started else candidate_year - 1
LATEST_SEASON_YEAR = max(latest_active_year, PROJECT_START_SEASON_YEAR)

SEASON_YEARS = list(range(PROJECT_START_SEASON_YEAR, LATEST_SEASON_YEAR + 1))
print(f"Relevant season years: {SEASON_YEARS}")

for season_year in SEASON_YEARS:
    is_latest = season_year == LATEST_SEASON_YEAR

    OUTPUT_PATH = Path(f"raw/{season_year}/soccerdata_fbref/player_match_stats_keepers.csv")
    S3_KEY = f"raw/{season_year}/soccerdata_fbref/player_match_stats_keepers.csv"

    if not is_latest and OUTPUT_PATH.exists():
        print(f"Skipping {season_year} - already saved locally.")
        continue

    print(f"Fetching player match stats (keepers) for {season_year}...")
    fbref = sd.FBref(leagues="ENG-Premier League", seasons=season_year)
    player_match_df = fbref.read_player_match_stats(stat_type='keepers')
    player_match_df = player_match_df.reset_index()

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    player_match_df.to_csv(OUTPUT_PATH, index=False)
    print(f"Saved response to {OUTPUT_PATH.resolve()}")

    body = player_match_df.to_csv(index=False).encode("utf-8")
    s3_client.put_object(
        Bucket=S3_BUCKET,
        Key=S3_KEY,
        Body=body,
        ContentType="text/csv",
    )
    print(f"Uploaded to s3://{S3_BUCKET}/{S3_KEY}")

Team Season Stats - Standard

In [ ]:
import requests
import soccerdata as sd
from pathlib import Path
import os
import boto3
from datetime import date
from dotenv import load_dotenv
load_dotenv()

HEADERS = {
    "X-Auth-Token": os.getenv("FOOTBALL_DATA_ORG_API_KEY"),
}
S3_BUCKET = os.getenv("S3_BUCKET")
PROJECT_START_SEASON_YEAR = 2025

session = boto3.Session(
    profile_name=os.getenv("AWS_PROFILE"),
    region_name="ap-south-1",
)
s3_client = session.client("s3")

competition_resp = requests.get(
    "https://api.football-data.org/v4/competitions/PL",
    headers=HEADERS,
)
competition_resp.raise_for_status()
current_season = competition_resp.json()["currentSeason"]

start_date = date.fromisoformat(current_season["startDate"])
candidate_year = start_date.year
season_has_started = date.today() >= start_date

latest_active_year = candidate_year if season_has_started else candidate_year - 1
LATEST_SEASON_YEAR = max(latest_active_year, PROJECT_START_SEASON_YEAR)

SEASON_YEARS = list(range(PROJECT_START_SEASON_YEAR, LATEST_SEASON_YEAR + 1))
print(f"Relevant season years: {SEASON_YEARS}")

for season_year in SEASON_YEARS:
    is_latest = season_year == LATEST_SEASON_YEAR

    OUTPUT_PATH = Path(f"raw/{season_year}/soccerdata_fbref/team_season_standard_stats.csv")
    S3_KEY = f"raw/{season_year}/soccerdata_fbref/team_season_standard_stats.csv"

    if not is_latest and OUTPUT_PATH.exists():
        print(f"Skipping {season_year} - already saved locally.")
        continue

    print(f"Fetching team season stats (standard) for {season_year}...")
    fbref = sd.FBref(leagues="ENG-Premier League", seasons=season_year)
    team_season_df = fbref.read_team_season_stats(stat_type='standard')
    team_season_df = team_season_df.reset_index()

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    team_season_df.to_csv(OUTPUT_PATH, index=False)
    print(f"Saved response to {OUTPUT_PATH.resolve()}")

    body = team_season_df.to_csv(index=False).encode("utf-8")
    s3_client.put_object(
        Bucket=S3_BUCKET,
        Key=S3_KEY,
        Body=body,
        ContentType="text/csv",
    )
    print(f"Uploaded to s3://{S3_BUCKET}/{S3_KEY}")

Team Season Stats - Shooting

In [ ]:
import requests
import soccerdata as sd
from pathlib import Path
import os
import boto3
from datetime import date
from dotenv import load_dotenv
load_dotenv()

HEADERS = {
    "X-Auth-Token": os.getenv("FOOTBALL_DATA_ORG_API_KEY"),
}
S3_BUCKET = os.getenv("S3_BUCKET")
PROJECT_START_SEASON_YEAR = 2025

session = boto3.Session(
    profile_name=os.getenv("AWS_PROFILE"),
    region_name="ap-south-1",
)
s3_client = session.client("s3")

competition_resp = requests.get(
    "https://api.football-data.org/v4/competitions/PL",
    headers=HEADERS,
)
competition_resp.raise_for_status()
current_season = competition_resp.json()["currentSeason"]

start_date = date.fromisoformat(current_season["startDate"])
candidate_year = start_date.year
season_has_started = date.today() >= start_date

latest_active_year = candidate_year if season_has_started else candidate_year - 1
LATEST_SEASON_YEAR = max(latest_active_year, PROJECT_START_SEASON_YEAR)

SEASON_YEARS = list(range(PROJECT_START_SEASON_YEAR, LATEST_SEASON_YEAR + 1))
print(f"Relevant season years: {SEASON_YEARS}")

for season_year in SEASON_YEARS:
    is_latest = season_year == LATEST_SEASON_YEAR

    OUTPUT_PATH = Path(f"raw/{season_year}/soccerdata_fbref/team_season_shooting_stats.csv")
    S3_KEY = f"raw/{season_year}/soccerdata_fbref/team_season_shooting_stats.csv"

    if not is_latest and OUTPUT_PATH.exists():
        print(f"Skipping {season_year} - already saved locally.")
        continue

    print(f"Fetching team season stats (shooting) for {season_year}...")
    fbref = sd.FBref(leagues="ENG-Premier League", seasons=season_year)
    team_season_df = fbref.read_team_season_stats(stat_type='shooting')
    team_season_df = team_season_df.reset_index()

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    team_season_df.to_csv(OUTPUT_PATH, index=False)
    print(f"Saved response to {OUTPUT_PATH.resolve()}")

    body = team_season_df.to_csv(index=False).encode("utf-8")
    s3_client.put_object(
        Bucket=S3_BUCKET,
        Key=S3_KEY,
        Body=body,
        ContentType="text/csv",
    )
    print(f"Uploaded to s3://{S3_BUCKET}/{S3_KEY}")

Team Season Stats - keeper

In [ ]:
import requests
import soccerdata as sd
from pathlib import Path
import os
import boto3
from datetime import date
from dotenv import load_dotenv
load_dotenv()

HEADERS = {
    "X-Auth-Token": os.getenv("FOOTBALL_DATA_ORG_API_KEY"),
}
S3_BUCKET = os.getenv("S3_BUCKET")
PROJECT_START_SEASON_YEAR = 2025

session = boto3.Session(
    profile_name=os.getenv("AWS_PROFILE"),
    region_name="ap-south-1",
)
s3_client = session.client("s3")

competition_resp = requests.get(
    "https://api.football-data.org/v4/competitions/PL",
    headers=HEADERS,
)
competition_resp.raise_for_status()
current_season = competition_resp.json()["currentSeason"]

start_date = date.fromisoformat(current_season["startDate"])
candidate_year = start_date.year
season_has_started = date.today() >= start_date

latest_active_year = candidate_year if season_has_started else candidate_year - 1
LATEST_SEASON_YEAR = max(latest_active_year, PROJECT_START_SEASON_YEAR)

SEASON_YEARS = list(range(PROJECT_START_SEASON_YEAR, LATEST_SEASON_YEAR + 1))
print(f"Relevant season years: {SEASON_YEARS}")

for season_year in SEASON_YEARS:
    is_latest = season_year == LATEST_SEASON_YEAR

    OUTPUT_PATH = Path(f"raw/{season_year}/soccerdata_fbref/team_season_keeper_stats.csv")
    S3_KEY = f"raw/{season_year}/soccerdata_fbref/team_season_keeper_stats.csv"

    if not is_latest and OUTPUT_PATH.exists():
        print(f"Skipping {season_year} - already saved locally.")
        continue

    print(f"Fetching team season stats (keeper) for {season_year}...")
    fbref = sd.FBref(leagues="ENG-Premier League", seasons=season_year)
    team_season_df = fbref.read_team_season_stats(stat_type='keeper')
    team_season_df = team_season_df.reset_index()

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    team_season_df.to_csv(OUTPUT_PATH, index=False)
    print(f"Saved response to {OUTPUT_PATH.resolve()}")

    body = team_season_df.to_csv(index=False).encode("utf-8")
    s3_client.put_object(
        Bucket=S3_BUCKET,
        Key=S3_KEY,
        Body=body,
        ContentType="text/csv",
    )
    print(f"Uploaded to s3://{S3_BUCKET}/{S3_KEY}")

Team Season Stats - playing_time

In [ ]:
import requests
import soccerdata as sd
from pathlib import Path
import os
import boto3
from datetime import date
from dotenv import load_dotenv
load_dotenv()

HEADERS = {
    "X-Auth-Token": os.getenv("FOOTBALL_DATA_ORG_API_KEY"),
}
S3_BUCKET = os.getenv("S3_BUCKET")
PROJECT_START_SEASON_YEAR = 2025

session = boto3.Session(
    profile_name=os.getenv("AWS_PROFILE"),
    region_name="ap-south-1",
)
s3_client = session.client("s3")

competition_resp = requests.get(
    "https://api.football-data.org/v4/competitions/PL",
    headers=HEADERS,
)
competition_resp.raise_for_status()
current_season = competition_resp.json()["currentSeason"]

start_date = date.fromisoformat(current_season["startDate"])
candidate_year = start_date.year
season_has_started = date.today() >= start_date

latest_active_year = candidate_year if season_has_started else candidate_year - 1
LATEST_SEASON_YEAR = max(latest_active_year, PROJECT_START_SEASON_YEAR)

SEASON_YEARS = list(range(PROJECT_START_SEASON_YEAR, LATEST_SEASON_YEAR + 1))
print(f"Relevant season years: {SEASON_YEARS}")

for season_year in SEASON_YEARS:
    is_latest = season_year == LATEST_SEASON_YEAR

    OUTPUT_PATH = Path(f"raw/{season_year}/soccerdata_fbref/team_season_playing_time_stats.csv")
    S3_KEY = f"raw/{season_year}/soccerdata_fbref/team_season_playing_time_stats.csv"

    if not is_latest and OUTPUT_PATH.exists():
        print(f"Skipping {season_year} - already saved locally.")
        continue

    print(f"Fetching team season stats (playing_time) for {season_year}...")
    fbref = sd.FBref(leagues="ENG-Premier League", seasons=season_year)
    team_season_df = fbref.read_team_season_stats(stat_type='playing_time')
    team_season_df = team_season_df.reset_index()

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    team_season_df.to_csv(OUTPUT_PATH, index=False)
    print(f"Saved response to {OUTPUT_PATH.resolve()}")

    body = team_season_df.to_csv(index=False).encode("utf-8")
    s3_client.put_object(
        Bucket=S3_BUCKET,
        Key=S3_KEY,
        Body=body,
        ContentType="text/csv",
    )
    print(f"Uploaded to s3://{S3_BUCKET}/{S3_KEY}")

Team Season Stats - Misc

In [ ]:
import requests
import soccerdata as sd
from pathlib import Path
import os
import boto3
from datetime import date
from dotenv import load_dotenv
load_dotenv()

HEADERS = {
    "X-Auth-Token": os.getenv("FOOTBALL_DATA_ORG_API_KEY"),
}
S3_BUCKET = os.getenv("S3_BUCKET")
PROJECT_START_SEASON_YEAR = 2025

session = boto3.Session(
    profile_name=os.getenv("AWS_PROFILE"),
    region_name="ap-south-1",
)
s3_client = session.client("s3")

competition_resp = requests.get(
    "https://api.football-data.org/v4/competitions/PL",
    headers=HEADERS,
)
competition_resp.raise_for_status()
current_season = competition_resp.json()["currentSeason"]

start_date = date.fromisoformat(current_season["startDate"])
candidate_year = start_date.year
season_has_started = date.today() >= start_date

latest_active_year = candidate_year if season_has_started else candidate_year - 1
LATEST_SEASON_YEAR = max(latest_active_year, PROJECT_START_SEASON_YEAR)

SEASON_YEARS = list(range(PROJECT_START_SEASON_YEAR, LATEST_SEASON_YEAR + 1))
print(f"Relevant season years: {SEASON_YEARS}")

for season_year in SEASON_YEARS:
    is_latest = season_year == LATEST_SEASON_YEAR

    OUTPUT_PATH = Path(f"raw/{season_year}/soccerdata_fbref/team_season_misc_stats.csv")
    S3_KEY = f"raw/{season_year}/soccerdata_fbref/team_season_misc_stats.csv"

    if not is_latest and OUTPUT_PATH.exists():
        print(f"Skipping {season_year} - already saved locally.")
        continue

    print(f"Fetching team season stats (misc) for {season_year}...")
    fbref = sd.FBref(leagues="ENG-Premier League", seasons=season_year)
    team_season_df = fbref.read_team_season_stats(stat_type='misc')
    team_season_df = team_season_df.reset_index()

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    team_season_df.to_csv(OUTPUT_PATH, index=False)
    print(f"Saved response to {OUTPUT_PATH.resolve()}")

    body = team_season_df.to_csv(index=False).encode("utf-8")
    s3_client.put_object(
        Bucket=S3_BUCKET,
        Key=S3_KEY,
        Body=body,
        ContentType="text/csv",
    )
    print(f"Uploaded to s3://{S3_BUCKET}/{S3_KEY}")

Team Match Stats

In [ ]:
import requests
import soccerdata as sd
from pathlib import Path
import os
import boto3
from datetime import date
from dotenv import load_dotenv
load_dotenv()

HEADERS = {
    "X-Auth-Token": os.getenv("FOOTBALL_DATA_ORG_API_KEY"),
}
S3_BUCKET = os.getenv("S3_BUCKET")
PROJECT_START_SEASON_YEAR = 2025

session = boto3.Session(
    profile_name=os.getenv("AWS_PROFILE"),
    region_name="ap-south-1",
)
s3_client = session.client("s3")

competition_resp = requests.get(
    "https://api.football-data.org/v4/competitions/PL",
    headers=HEADERS,
)
competition_resp.raise_for_status()
current_season = competition_resp.json()["currentSeason"]

start_date = date.fromisoformat(current_season["startDate"])
candidate_year = start_date.year
season_has_started = date.today() >= start_date

latest_active_year = candidate_year if season_has_started else candidate_year - 1
LATEST_SEASON_YEAR = max(latest_active_year, PROJECT_START_SEASON_YEAR)

SEASON_YEARS = list(range(PROJECT_START_SEASON_YEAR, LATEST_SEASON_YEAR + 1))
print(f"Relevant season years: {SEASON_YEARS}")

for season_year in SEASON_YEARS:
    is_latest = season_year == LATEST_SEASON_YEAR

    OUTPUT_PATH = Path(f"raw/{season_year}/soccerdata_fbref/team_match_schedule_stats.csv")
    S3_KEY = f"raw/{season_year}/soccerdata_fbref/team_match_schedule_stats.csv"

    if not is_latest and OUTPUT_PATH.exists():
        print(f"Skipping {season_year} - already saved locally.")
        continue

    print(f"Fetching team match stats (schedule) for {season_year}...")
    fbref = sd.FBref(leagues="ENG-Premier League", seasons=season_year)
    team_match_df = fbref.read_team_match_stats(stat_type='schedule')
    team_match_df = team_match_df.reset_index()

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    team_match_df.to_csv(OUTPUT_PATH, index=False)
    print(f"Saved response to {OUTPUT_PATH.resolve()}")

    body = team_match_df.to_csv(index=False).encode("utf-8")
    s3_client.put_object(
        Bucket=S3_BUCKET,
        Key=S3_KEY,
        Body=body,
        ContentType="text/csv",
    )
    print(f"Uploaded to s3://{S3_BUCKET}/{S3_KEY}")

Team Match Stats - shooting

In [ ]:
import requests
import soccerdata as sd
from pathlib import Path
import os
import boto3
from datetime import date
from dotenv import load_dotenv
load_dotenv()

HEADERS = {
    "X-Auth-Token": os.getenv("FOOTBALL_DATA_ORG_API_KEY"),
}
S3_BUCKET = os.getenv("S3_BUCKET")
PROJECT_START_SEASON_YEAR = 2025

session = boto3.Session(
    profile_name=os.getenv("AWS_PROFILE"),
    region_name="ap-south-1",
)
s3_client = session.client("s3")

competition_resp = requests.get(
    "https://api.football-data.org/v4/competitions/PL",
    headers=HEADERS,
)
competition_resp.raise_for_status()
current_season = competition_resp.json()["currentSeason"]

start_date = date.fromisoformat(current_season["startDate"])
candidate_year = start_date.year
season_has_started = date.today() >= start_date

latest_active_year = candidate_year if season_has_started else candidate_year - 1
LATEST_SEASON_YEAR = max(latest_active_year, PROJECT_START_SEASON_YEAR)

SEASON_YEARS = list(range(PROJECT_START_SEASON_YEAR, LATEST_SEASON_YEAR + 1))
print(f"Relevant season years: {SEASON_YEARS}")

for season_year in SEASON_YEARS:
    is_latest = season_year == LATEST_SEASON_YEAR

    OUTPUT_PATH = Path(f"raw/{season_year}/soccerdata_fbref/team_match_shooting_stats.csv")
    S3_KEY = f"raw/{season_year}/soccerdata_fbref/team_match_shooting_stats.csv"

    if not is_latest and OUTPUT_PATH.exists():
        print(f"Skipping {season_year} - already saved locally.")
        continue

    print(f"Fetching team match stats (shooting) for {season_year}...")
    fbref = sd.FBref(leagues="ENG-Premier League", seasons=season_year)
    team_match_df = fbref.read_team_match_stats(stat_type='shooting')
    team_match_df = team_match_df.reset_index()

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    team_match_df.to_csv(OUTPUT_PATH, index=False)
    print(f"Saved response to {OUTPUT_PATH.resolve()}")

    body = team_match_df.to_csv(index=False).encode("utf-8")
    s3_client.put_object(
        Bucket=S3_BUCKET,
        Key=S3_KEY,
        Body=body,
        ContentType="text/csv",
    )
    print(f"Uploaded to s3://{S3_BUCKET}/{S3_KEY}")

Team Match Stats - Keeper

In [ ]:
import requests
import soccerdata as sd
from pathlib import Path
import os
import boto3
from datetime import date
from dotenv import load_dotenv
load_dotenv()

HEADERS = {
    "X-Auth-Token": os.getenv("FOOTBALL_DATA_ORG_API_KEY"),
}
S3_BUCKET = os.getenv("S3_BUCKET")
PROJECT_START_SEASON_YEAR = 2025

session = boto3.Session(
    profile_name=os.getenv("AWS_PROFILE"),
    region_name="ap-south-1",
)
s3_client = session.client("s3")

competition_resp = requests.get(
    "https://api.football-data.org/v4/competitions/PL",
    headers=HEADERS,
)
competition_resp.raise_for_status()
current_season = competition_resp.json()["currentSeason"]

start_date = date.fromisoformat(current_season["startDate"])
candidate_year = start_date.year
season_has_started = date.today() >= start_date

latest_active_year = candidate_year if season_has_started else candidate_year - 1
LATEST_SEASON_YEAR = max(latest_active_year, PROJECT_START_SEASON_YEAR)

SEASON_YEARS = list(range(PROJECT_START_SEASON_YEAR, LATEST_SEASON_YEAR + 1))
print(f"Relevant season years: {SEASON_YEARS}")

for season_year in SEASON_YEARS:
    is_latest = season_year == LATEST_SEASON_YEAR

    OUTPUT_PATH = Path(f"raw/{season_year}/soccerdata_fbref/team_match_keeper_stats.csv")
    S3_KEY = f"raw/{season_year}/soccerdata_fbref/team_match_keeper_stats.csv"

    if not is_latest and OUTPUT_PATH.exists():
        print(f"Skipping {season_year} - already saved locally.")
        continue

    print(f"Fetching team match stats (keeper) for {season_year}...")
    fbref = sd.FBref(leagues="ENG-Premier League", seasons=season_year)
    team_match_df = fbref.read_team_match_stats(stat_type='keeper')
    team_match_df = team_match_df.reset_index()

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    team_match_df.to_csv(OUTPUT_PATH, index=False)
    print(f"Saved response to {OUTPUT_PATH.resolve()}")

    body = team_match_df.to_csv(index=False).encode("utf-8")
    s3_client.put_object(
        Bucket=S3_BUCKET,
        Key=S3_KEY,
        Body=body,
        ContentType="text/csv",
    )
    print(f"Uploaded to s3://{S3_BUCKET}/{S3_KEY}")

Team Match Stats - misc

In [ ]:
import requests
import soccerdata as sd
from pathlib import Path
import os
import boto3
from datetime import date
from dotenv import load_dotenv
load_dotenv()

HEADERS = {
    "X-Auth-Token": os.getenv("FOOTBALL_DATA_ORG_API_KEY"),
}
S3_BUCKET = os.getenv("S3_BUCKET")
PROJECT_START_SEASON_YEAR = 2025

session = boto3.Session(
    profile_name=os.getenv("AWS_PROFILE"),
    region_name="ap-south-1",
)
s3_client = session.client("s3")

competition_resp = requests.get(
    "https://api.football-data.org/v4/competitions/PL",
    headers=HEADERS,
)
competition_resp.raise_for_status()
current_season = competition_resp.json()["currentSeason"]

start_date = date.fromisoformat(current_season["startDate"])
candidate_year = start_date.year
season_has_started = date.today() >= start_date

latest_active_year = candidate_year if season_has_started else candidate_year - 1
LATEST_SEASON_YEAR = max(latest_active_year, PROJECT_START_SEASON_YEAR)

SEASON_YEARS = list(range(PROJECT_START_SEASON_YEAR, LATEST_SEASON_YEAR + 1))
print(f"Relevant season years: {SEASON_YEARS}")

for season_year in SEASON_YEARS:
    is_latest = season_year == LATEST_SEASON_YEAR

    OUTPUT_PATH = Path(f"raw/{season_year}/soccerdata_fbref/team_match_misc_stats.csv")
    S3_KEY = f"raw/{season_year}/soccerdata_fbref/team_match_misc_stats.csv"

    if not is_latest and OUTPUT_PATH.exists():
        print(f"Skipping {season_year} - already saved locally.")
        continue

    print(f"Fetching team match stats (misc) for {season_year}...")
    fbref = sd.FBref(leagues="ENG-Premier League", seasons=season_year)
    team_match_df = fbref.read_team_match_stats(stat_type='misc')
    team_match_df = team_match_df.reset_index()

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    team_match_df.to_csv(OUTPUT_PATH, index=False)
    print(f"Saved response to {OUTPUT_PATH.resolve()}")

    body = team_match_df.to_csv(index=False).encode("utf-8")
    s3_client.put_object(
        Bucket=S3_BUCKET,
        Key=S3_KEY,
        Body=body,
        ContentType="text/csv",
    )
    print(f"Uploaded to s3://{S3_BUCKET}/{S3_KEY}")

In [ ]:
import asyncio, json, os, re, requests
import websockets
from confluent_kafka import Producer
from dotenv import load_dotenv

load_dotenv()
API_KEY = os.getenv("API_FOOTBALL_KEY")
TOURNAMENT_ID = 17
TOPIC = "raw.sportsapipro-events"
RAW_LOG_FILE = "sportsapipro_raw.jsonl"

MATCH_CHANNEL_SUFFIXES = ("", ":incidents", ":stats", ":lineups", ":odds")

ACTIVE_STATUSES = ("notstarted", "inprogress")

producer = Producer({
    "bootstrap.servers": "localhost:9092",
    "acks": "all",
    "enable.idempotence": True,
})

def delivery_report(err, msg):
    if err is not None:
        print(f"KAFKA DELIVERY FAILED: {err}")

def is_premier_league(tournament: dict) -> bool:
    """Defensive check — pre-game fixtures don't always have uniqueTournament populated yet."""
    tournament = tournament or {}
    unique_id = (tournament.get("uniqueTournament") or {}).get("id")
    slug = tournament.get("slug")
    return unique_id == TOURNAMENT_ID or slug == "premier-league"

def get_todays_pl_matches():
    """One-off REST call at startup — seeds any PL matches already live/upcoming today."""
    resp = requests.get(
        "https://api.sportsapipro.com/v2/football/api/today",
        headers={"x-api-key": API_KEY},
    )
    resp.raise_for_status()
    events = resp.json()["events"]

    matches = {}
    for e in events:
        if is_premier_league(e.get("tournament")):
            matches[e["id"]] = e["status"]["type"]
        else:
            print(f"skipped (not PL): id={e.get('id')} tournament={(e.get('tournament') or {}).get('name')}")
    return matches

match_key_re = re.compile(r"match:(\d+)")

def kafka_send(raw_message: str, f):
    f.write(raw_message + "\n")
    f.flush()
    m = match_key_re.search(raw_message)
    key = m.group(1) if m else "unkeyed"
    while True:
        try:
            producer.produce(TOPIC, key=key, value=raw_message, callback=delivery_report)
            break
        except BufferError:
            producer.poll(0.1)
    producer.poll(0)

async def subscribe_match(ws, match_id, subscribed):
    for suffix in MATCH_CHANNEL_SUFFIXES:
        ch = f"match:{match_id}{suffix}"
        if ch not in subscribed:
            await ws.send(json.dumps({"action": "subscribe", "channel": ch}))
            subscribed.add(ch)
            print(f"subscribed: {ch}")

async def unsubscribe_match(ws, match_id, subscribed):
    for suffix in MATCH_CHANNEL_SUFFIXES:
        ch = f"match:{match_id}{suffix}"
        if ch in subscribed:
            await ws.send(json.dumps({"action": "unsubscribe", "channel": ch}))
            subscribed.discard(ch)
            print(f"unsubscribed: {ch}")

async def keepalive(ws):
    while True:
        await asyncio.sleep(30)
        await ws.send(json.dumps({"action": "ping", "channel": "live-scores"}))

async def watch():
    uri = f"wss://api.sportsapipro.com/v2/football/ws?x-api-key={API_KEY}"
    live_matches = get_todays_pl_matches()
    backoff = 1

    with open(RAW_LOG_FILE, "a", encoding="utf-8") as f:
        while True:
            subscribed = set()
            try:
                async with websockets.connect(uri) as ws:
                    backoff = 1

                    await ws.send(json.dumps({"action": "subscribe", "channel": "live-scores:football"}))
                    subscribed.add("live-scores:football")
                    print("subscribed: live-scores:football")

                    for mid, status in list(live_matches.items()):
                        if status in ACTIVE_STATUSES:
                            await subscribe_match(ws, mid, subscribed)

                    ping_task = asyncio.create_task(keepalive(ws))
                    try:
                        async for message in ws:
                            kafka_send(message, f)
                            try:
                                frame = json.loads(message)
                            except json.JSONDecodeError:
                                print(f"non-JSON frame (still saved raw): {message[:100]}")
                                continue

                            print(f"→ {frame.get('channel')} [{frame.get('type')}]")

                            if frame.get("channel") == "live-scores:football":
                                for game in frame.get("data", {}).get("games", []):
                                    mid = game["id"]
                                    if not is_premier_league(game.get("tournament")):
                                        continue
                                    status = game["status"]["type"]
                                    prev = live_matches.get(mid)
                                    live_matches[mid] = status
                                    if status == "inprogress" and prev != "inprogress":
                                        await subscribe_match(ws, mid, subscribed)
                                    elif status == "finished" and prev == "inprogress":
                                        await unsubscribe_match(ws, mid, subscribed)
                    finally:
                        ping_task.cancel()

            except (websockets.exceptions.ConnectionClosed, OSError) as e:
                print(f"disconnected ({e}) — retrying in {backoff}s")
                await asyncio.sleep(backoff)
                backoff = min(backoff * 2, 30)

try:
    await watch()
finally:
    print("flushing producer — waiting for any pending messages to be delivered...")
    producer.flush(timeout=10)

In [ ]:
from confluent_kafka import Consumer, TopicPartition
import json
import pandas as pd

BOOTSTRAP_SERVERS = "localhost:9092"
TOPIC = "raw.sportsapipro-events"
MATCH_ID = "16363651"

GROUP_ID = f"notebook-replay-{MATCH_ID}-v2"

consumer = Consumer({
    "bootstrap.servers": BOOTSTRAP_SERVERS,
    "group.id": GROUP_ID,
    "enable.auto.commit": False,
    "auto.offset.reset": "earliest",
})

metadata = consumer.list_topics(TOPIC, timeout=10)
partitions = sorted(metadata.topics[TOPIC].partitions.keys())

print(f"Topic: {TOPIC}")
print(f"Partitions: {partitions}")
print(f"Looking for match: {MATCH_ID}")
print()

start_offsets = {}
end_offsets = {}

for partition in partitions:
    tp = TopicPartition(TOPIC, partition)

    low, high = consumer.get_watermark_offsets(
        tp,
        timeout=10,
        cached=False
    )

    start_offsets[partition] = low
    end_offsets[partition] = high

    print(
        f"Partition {partition}: "
        f"{low} → {high} "
        f"({high - low} messages)"
    )
consumer.assign([
    TopicPartition(TOPIC, partition, start_offsets[partition])
    for partition in partitions
])

messages = []

while True:

    msg = consumer.poll(1.0)

    if msg is None:
        continue

    if msg.error():
        print(f"Kafka error: {msg.error()}")
        continue

    partition = msg.partition()
    offset = msg.offset()

    if offset >= end_offsets[partition]:
        continue

    key = msg.key().decode("utf-8") if msg.key() else None

    if key == MATCH_ID:

        raw = msg.value().decode("utf-8")

        try:
            data = json.loads(raw)

            messages.append({
                "partition": partition,
                "offset": offset,
                "key": key,
                "channel": data.get("channel"),
                "type": data.get("type"),
                "data": data,
                "raw": raw,
            })

        except json.JSONDecodeError:
            print(
                f"Invalid JSON: "
                f"partition={partition}, offset={offset}"
            )

    positions = consumer.position([
        TopicPartition(TOPIC, p)
        for p in partitions
    ])

    if all(
        tp.offset >= end_offsets[tp.partition]
        for tp in positions
    ):
        break

consumer.close()

In [16]:
from collections import Counter
import pandas as pd

for m in messages:
    parts = (m["channel"] or "").split(":")
    m["kind"] = parts[2] if len(parts) > 2 else ("match" if len(parts) == 2 else None)

print("all messages by (kind, type):")
for (kind, mtype), n in sorted(Counter((m["kind"], m["type"]) for m in messages).items(), key=str):
    print(f"  {str(kind):<10} {str(mtype):<12} {n}")

KEEP_TYPES = {"snapshot", "update"}

kept = [
    m for m in messages
    if m["type"] in KEEP_TYPES and m["kind"] and "odds" not in m["kind"]
]

match_msgs    = [m for m in kept if m["kind"] == "match"]
incident_msgs = [m for m in kept if m["kind"] == "incidents"]
stats_msgs    = [m for m in kept if m["kind"] == "stats"]
lineup_msgs   = [m for m in kept if m["kind"] == "lineups"]

print(f"\nkept {len(kept)} of {len(messages)}")
print(f"match {len(match_msgs)} | incidents {len(incident_msgs)} | stats {len(stats_msgs)} | lineups {len(lineup_msgs)}")
print("unhandled kinds:", sorted({m["kind"] for m in kept} - {"match", "incidents", "stats", "lineups"}))

all messages by (kind, type):
  incidents  snapshot     5
  incidents  subscribed   5
  incidents  update       12
  lineups    snapshot     5
  lineups    subscribed   5
  lineups    update       53
  match      subscribed   5
  match      update       42
  odds       snapshot     5
  odds       subscribed   5
  odds       update       14
  stats      snapshot     5
  stats      subscribed   5
  stats      update       26

kept 148 of 192
match 42 | incidents 17 | stats 31 | lineups 58
unhandled kinds: []

In [17]:
rows = []
for m in match_msgs:
    env = m["data"]
    rows.append({
        **env["data"],
        "msg_type": m["type"],
        "offset": m["offset"],
        "event_ts": pd.to_datetime(env["timestamp"], unit="ms", utc=True),
    })

df_live_score = pd.DataFrame(rows).rename(columns={"id": "match_id"})
print(df_live_score.shape)
print(df_live_score.columns.tolist())
df_live_score.head(10)

(42, 32)
['homeScore.period1', 'homeScore.normaltime', 'awayScore.period1', 'awayScore.normaltime', 'changes.changeTimestamp', 'match_id', 'msg_type', 'offset', 'event_ts', 'homeScore.current', 'homeScore.display', 'status.code', 'status.description', 'statusDescription', 'time.lastPeriodEndTimestamp', 'lastPeriod', 'time.injuryTime1', 'time.currentPeriodStartTimestamp', 'time.initial', 'time.max', 'time.extra', 'currentPeriodStartTimestamp', 'statusTime', 'homeScore.period2', 'awayScore.period2', 'eventState.statusIndicator', 'eventState.timestamp', 'varInProgress', 'cardsCode', 'winnerCode', 'status.type', 'time.injuryTime2']

,homeScore.period1,homeScore.normaltime,awayScore.period1,awayScore.normaltime,changes.changeTimestamp,match_id,msg_type,offset,event_ts,homeScore.current,...,statusTime,homeScore.period2,awayScore.period2,eventState.statusIndicator,eventState.timestamp,varInProgress,cardsCode,winnerCode,status.type,time.injuryTime2
0,0.0,0.0,0.0,0.0,1789826504,16363651,update,197,2026-09-19 14:01:44.778000+00:00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,0.0,0.0,0.0,1789826504,16363651,update,198,2026-09-19 14:01:44.779000+00:00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.0,0.0,0.0,0.0,1789826504,16363651,update,199,2026-09-19 14:01:44.779000+00:00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,NaN,NaN,NaN,1789827029,16363651,update,256,2026-09-19 14:10:29.276000+00:00,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.0,NaN,NaN,NaN,1789827029,16363651,update,257,2026-09-19 14:10:29.366000+00:00,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1.0,NaN,NaN,NaN,1789827029,16363651,update,258,2026-09-19 14:10:29.367000+00:00,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,1.0,NaN,NaN,1789827248,16363651,update,285,2026-09-19 14:14:08.144000+00:00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,1.0,NaN,NaN,1789827248,16363651,update,286,2026-09-19 14:14:08.159000+00:00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,1.0,NaN,NaN,1789827248,16363651,update,287,2026-09-19 14:14:08.160000+00:00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,1789829425,16363651,update,504,2026-09-19 14:50:26.486000+00:00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
rows = []
for m in incident_msgs:
    env = m["data"]
    for inc in env["data"].get("incidents", []):
        rows.append({
            **inc,
            "match_id": int(MATCH_ID),
            "msg_type": m["type"],
            "offset": m["offset"],
            "event_ts": pd.to_datetime(env["timestamp"], unit="ms", utc=True),
        })

df_live_incidents = pd.json_normalize(rows, sep="_")

if "addedTime" in df_live_incidents.columns:
    df_live_incidents["addedTime"] = df_live_incidents["addedTime"].where(df_live_incidents["addedTime"] != 999)

print(df_live_incidents.shape)
print(df_live_incidents.columns.tolist())
print(df_live_incidents["incidentType"].value_counts())
df_live_incidents.head(10)

(165, 121)
['text', 'homeScore', 'awayScore', 'isLive', 'time', 'addedTime', 'timeSeconds', 'incidentType', 'reversedPeriodTime', 'reversedPeriodTimeSeconds', 'periodTimeSeconds', 'match_id', 'msg_type', 'offset', 'event_ts', 'footballPassingNetworkAction', 'id', 'isHome', 'incidentClass', 'player_name', 'player_slug', 'player_shortName', 'player_position', 'player_jerseyNumber', 'player_height', 'player_userCount', 'player_gender', 'player_sofascoreId', 'player_id', 'player_marketValueCurrency', 'player_dateOfBirthTimestamp', 'player_proposedMarketValueRaw_value', 'player_proposedMarketValueRaw_currency', 'player_fieldTranslations_nameTranslation_ar', 'player_fieldTranslations_nameTranslation_bn', 'player_fieldTranslations_nameTranslation_hi', 'player_fieldTranslations_nameTranslation_ru', 'player_fieldTranslations_shortNameTranslation_ar', 'player_fieldTranslations_shortNameTranslation_bn', 'player_fieldTranslations_shortNameTranslation_hi', 'player_fieldTranslations_shortNameTranslation_ru', 'assist1_name', 'assist1_firstName', 'assist1_lastName', 'assist1_slug', 'assist1_shortName', 'assist1_position', 'assist1_jerseyNumber', 'assist1_height', 'assist1_userCount', 'assist1_gender', 'assist1_sofascoreId', 'assist1_id', 'assist1_marketValueCurrency', 'assist1_dateOfBirthTimestamp', 'assist1_proposedMarketValueRaw_value', 'assist1_proposedMarketValueRaw_currency', 'assist1_fieldTranslations_nameTranslation_ar', 'assist1_fieldTranslations_nameTranslation_bn', 'assist1_fieldTranslations_nameTranslation_hi', 'assist1_fieldTranslations_nameTranslation_ru', 'assist1_fieldTranslations_shortNameTranslation_ar', 'assist1_fieldTranslations_shortNameTranslation_bn', 'assist1_fieldTranslations_shortNameTranslation_hi', 'assist1_fieldTranslations_shortNameTranslation_ru', 'playerName', 'reason', 'rescinded', 'player_firstName', 'player_lastName', 'length', 'confirmed', 'injury', 'playerIn_name', 'playerIn_firstName', 'playerIn_lastName', 'playerIn_slug', 'playerIn_shortName', 'playerIn_position', 'playerIn_jerseyNumber', 'playerIn_height', 'playerIn_userCount', 'playerIn_gender', 'playerIn_sofascoreId', 'playerIn_id', 'playerIn_marketValueCurrency', 'playerIn_dateOfBirthTimestamp', 'playerIn_proposedMarketValueRaw_value', 'playerIn_proposedMarketValueRaw_currency', 'playerIn_fieldTranslations_nameTranslation_ar', 'playerIn_fieldTranslations_nameTranslation_bn', 'playerIn_fieldTranslations_nameTranslation_hi', 'playerIn_fieldTranslations_nameTranslation_ru', 'playerIn_fieldTranslations_shortNameTranslation_ar', 'playerIn_fieldTranslations_shortNameTranslation_bn', 'playerIn_fieldTranslations_shortNameTranslation_hi', 'playerIn_fieldTranslations_shortNameTranslation_ru', 'playerOut_name', 'playerOut_firstName', 'playerOut_lastName', 'playerOut_slug', 'playerOut_shortName', 'playerOut_position', 'playerOut_jerseyNumber', 'playerOut_height', 'playerOut_userCount', 'playerOut_gender', 'playerOut_sofascoreId', 'playerOut_id', 'playerOut_marketValueCurrency', 'playerOut_dateOfBirthTimestamp', 'playerOut_proposedMarketValueRaw_value', 'playerOut_proposedMarketValueRaw_currency', 'playerOut_fieldTranslations_nameTranslation_ar', 'playerOut_fieldTranslations_nameTranslation_bn', 'playerOut_fieldTranslations_nameTranslation_hi', 'playerOut_fieldTranslations_nameTranslation_ru', 'playerOut_fieldTranslations_shortNameTranslation_ar', 'playerOut_fieldTranslations_shortNameTranslation_bn', 'playerOut_fieldTranslations_shortNameTranslation_hi', 'playerOut_fieldTranslations_shortNameTranslation_ru']
incidentType
substitution    56
card            43
period          27
goal            16
injuryTime      15
varDecision      8
Name: count, dtype: int64

,text,homeScore,awayScore,isLive,time,addedTime,timeSeconds,incidentType,reversedPeriodTime,reversedPeriodTimeSeconds,...,playerOut_proposedMarketValueRaw_value,playerOut_proposedMarketValueRaw_currency,playerOut_fieldTranslations_nameTranslation_ar,playerOut_fieldTranslations_nameTranslation_bn,playerOut_fieldTranslations_nameTranslation_hi,playerOut_fieldTranslations_nameTranslation_ru,playerOut_fieldTranslations_shortNameTranslation_ar,playerOut_fieldTranslations_shortNameTranslation_bn,playerOut_fieldTranslations_shortNameTranslation_hi,playerOut_fieldTranslations_shortNameTranslation_ru
0,First half,0.0,0.0,True,45,NaN,2700.0,period,1,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,First half,1.0,0.0,True,45,NaN,2700.0,period,1,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,First half,1.0,0.0,True,45,NaN,2700.0,period,1,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,1.0,0.0,NaN,11,NaN,NaN,goal,35,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,First half,1.0,0.0,True,45,NaN,2700.0,period,1,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,1.0,0.0,NaN,11,NaN,NaN,goal,35,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,First half,1.0,0.0,True,45,NaN,2700.0,period,1,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,35,NaN,NaN,card,11,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,1.0,0.0,NaN,11,NaN,NaN,goal,35,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,HT,1.0,0.0,False,45,NaN,2700.0,period,1,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:

team_ids = {}
bad_lineups = []
for m in lineup_msgs:
    p = m["data"]["data"]
    if not p.get("home") or not p.get("away"):
        bad_lineups.append(m)
        continue
    for side in ("home", "away"):
        ids = [x["teamId"] for x in p[side].get("players", [])]
        if ids:
            team_ids.setdefault(side, max(set(ids), key=ids.count))   # mode: an academy sub carries a different teamId

print("team_ids:", team_ids)
print("lineup msgs without usable home/away:", len(bad_lineups))
for b in bad_lineups[:3]:
    print("  ", b["type"], b["offset"], str(b["data"]["data"])[:150])

TEAM_STATS = {                        
    "ballPossession": "possession",
    "expectedGoals": "xg",
    "bigChanceCreated": "big_chances",
    "totalShotsOnGoal": "shots_total",
    "shotsOffGoal": "shots_off_target",
    "goalkeeperSaves": "saves",
    "passes": "passes",
    "accuratePasses": "passes_accurate",
    "fouls": "fouls",
    "totalTackle": "tackles",
    "interceptionWon": "interceptions",
    "totalClearance": "clearances",
    "ballRecovery": "recoveries",
    "touchesInOppBox": "touches_opp_box",
    "finalThirdEntries": "final_third_entries",
    "duelWonPercent": "duels_won_pct",
}

rows = []
seen = set()
skipped_404 = 0

for m in stats_msgs:
    env = m["data"]
    p = env["data"]
    if "error" in p:
        skipped_404 += 1
        continue
    ts = pd.to_datetime(env["timestamp"], unit="ms", utc=True)

    for block in p.get("statistics", []):
        if block["period"] != "ALL":
            continue
        base = {"match_id": int(MATCH_ID), "msg_type": m["type"], "offset": m["offset"], "event_ts": ts}
        home = {**base, "side": "home", "team_id": team_ids.get("home")}
        away = {**base, "side": "away", "team_id": team_ids.get("away")}

        for g in block["groups"]:
            for it in g["statisticsItems"]:
                seen.add((g["groupName"], it["key"], it["name"]))
                col = TEAM_STATS.get(it["key"])
                if col and col not in home:
                    home[col] = it["homeValue"]
                    away[col] = it["awayValue"]
        rows += [home, away]

df_live_team_stats = pd.DataFrame(rows)
print(df_live_team_stats.shape, "| skipped 404 snapshots:", skipped_404)

df_stat_keys = (
    pd.DataFrame(sorted(seen), columns=["group", "key", "name"])
    .assign(kept=lambda x: x["key"].isin(TEAM_STATS))
)
df_live_team_stats.head(10)

team_ids: {'home': 48, 'away': 32}
lineup msgs without usable home/away: 1
   update 797 {'error': {'code': 403, 'reason': 'challenge'}}
(58, 22) | skipped 404 snapshots: 2

,match_id,msg_type,offset,event_ts,side,team_id,possession,xg,big_chances,shots_total,...,passes,tackles,shots_off_target,touches_opp_box,passes_accurate,final_third_entries,duels_won_pct,interceptions,recoveries,clearances
0,16363651,update,259,2026-09-19 14:10:29.629000+00:00,home,48,51,0.65,1,2,...,54,2,2,1,46,10,36,2,6,1
1,16363651,update,259,2026-09-19 14:10:29.629000+00:00,away,32,49,0.05,0,0,...,53,2,0,1,41,1,55,0,5,2
2,16363651,update,304,2026-09-19 14:16:51.924000+00:00,home,48,64,0.83,2,4,...,105,3,3,2,90,15,50,3,9,2
3,16363651,update,304,2026-09-19 14:16:51.924000+00:00,away,32,36,0.05,0,1,...,60,2,0,2,46,2,50,3,6,5
4,16363651,update,312,2026-09-19 14:18:21.107000+00:00,home,48,57,0.83,2,4,...,121,3,3,2,103,16,47,4,10,2
5,16363651,update,312,2026-09-19 14:18:21.107000+00:00,away,32,43,0.05,0,1,...,91,2,0,2,74,4,50,3,8,5
6,16363651,update,352,2026-09-19 14:24:57.933000+00:00,home,48,52,0.83,2,4,...,155,4,3,2,131,18,50,4,13,6
7,16363651,update,352,2026-09-19 14:24:57.933000+00:00,away,32,48,0.22,0,3,...,138,3,0,4,117,7,50,4,11,5
8,16363651,update,356,2026-09-19 14:26:03.891000+00:00,home,48,51,0.83,2,4,...,157,5,3,2,131,19,53,4,14,6
9,16363651,update,356,2026-09-19 14:26:03.891000+00:00,away,32,49,0.22,0,3,...,149,3,0,4,127,8,47,4,12,5

In [ ]:
PLAYER_STATS = {
    "minutesPlayed": "minutes",
    "touches": "touches",
    "totalPass": "passes",
    "accuratePass": "passes_accurate",
    "totalShots": "shots",
    "shotOffTarget": "shots_off_target",
    "expectedGoals": "xg",
    "expectedAssists": "xa",
    "duelWon": "duels_won",
    "duelLost": "duels_lost",
    "fouls": "fouls",
    "wasFouled": "was_fouled",
    "totalClearance": "clearances",
    "ballRecovery": "recoveries",
}

rows = []
for m in lineup_msgs:
    env = m["data"]
    p = env["data"]
    ts = pd.to_datetime(env["timestamp"], unit="ms", utc=True)

    for side in ("home", "away"):
        team = p.get(side)
        if not team or not team.get("players"):
            continue
        ids = [x["teamId"] for x in team["players"]]
        side_team_id = max(set(ids), key=ids.count)

        for x in team["players"]:
            row = {
                "match_id": int(MATCH_ID),
                "side": side,
                "team_id": side_team_id,
                "shirt_number": x["shirtNumber"],
                "player_name": x["player"]["name"],
                "position": x["position"],
                "is_sub": x["substitute"],
                "is_captain": x.get("captain", False),
                "formation": team.get("formation"),
                "confirmed": p.get("confirmed"),
                "msg_type": m["type"],
                "offset": m["offset"],
                "event_ts": ts,
            }
            s = x.get("statistics", {})
            for k, col in PLAYER_STATS.items():
                row[col] = s.get(k)
            rows.append(row)

df_live_lineups = pd.DataFrame(rows)
print(df_live_lineups.shape)
print(df_live_lineups.groupby(["side", "team_id"]).size())
df_live_lineups.head(10)

(2280, 27)
side  team_id
away  32         1140
home  48         1140
dtype: int64

,match_id,side,team_id,shirt_number,player_name,position,is_sub,is_captain,formation,confirmed,...,shots,shots_off_target,xg,xa,duels_won,duels_lost,fouls,was_fouled,clearances,recoveries
0,16363651,home,48,1,Jordan Pickford,G,False,False,4-2-3-1,True,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,16363651,home,48,2,Ainsley Maitland-Niles,D,False,False,4-2-3-1,True,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,16363651,home,48,6,James Tarkowski,D,False,True,4-2-3-1,True,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,16363651,home,48,4,Jarrad Branthwaite,D,False,False,4-2-3-1,True,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,16363651,home,48,16,Vitaliy Mykolenko,D,False,False,4-2-3-1,True,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,16363651,home,48,45,Harrison Armstrong,M,False,False,4-2-3-1,True,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,16363651,home,48,37,James Garner,M,False,False,4-2-3-1,True,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,16363651,home,48,22,Brennan Johnson,M,False,False,4-2-3-1,True,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,16363651,home,48,8,Kiernan Dewsbury-Hall,M,False,False,4-2-3-1,True,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,16363651,home,48,10,Jack Grealish,M,False,False,4-2-3-1,True,...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN